name: CI
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger update
        run: curl -Li https://jenkins.qhy04.com/buildByToken/build?job=Update%20Hoyo-Card-Assets&token=${{ secrets.BUILD_TOKEN }}&cause=git%20push
